### ISSUE TITLE
Unpacking tarball failed - can't add as Elixir dependency

### ISSUE THREAD

**Issue by frunox** [fireproofsocks/figlet#3]
Trying to add figlet as an elixir dependency, which is failing.  Other dependencies are installing correctly.

Elixir 1.12.3, Erlang/OTP 24.
Windows 10

Code:
```
defp deps do
    [
        {:cowrie, "~> 0.3.1"},
        {:figlet, "~> 0.2.0"},
        {:yaml_elixir, "~> 2.8`}
    ]
end
```
Error message

> New:
>    figlet 0.2.0
> * Updating figlet (Hex package)
> ** (Mix) Unpacking tarball failed: inner tarball error, not owner
> 

Procedure:
1.  Added cowrie and yaml_elixir to dependency list
2. Ran 'mix deps.get', no problems
3. Ran 'iex -S mix', no problems
4. Add figlet  to dependency list
5. Ran mix deps.get, got error message above.

Also, in VSCode using ElixirLS extension, when figlet is added in the mix.exs file, ElixirLS throws an exception.  This has not happened with any other dependency in any project I have created.

**Comment by fireproofsocks** [comment]
Thanks for filing this!  Sorry I'm seeing it just now (buried in Github notifications).  I suspect this might have something to do with how the figlet files are referenced... let me see if I can reproduce the issue.

**Comment by fireproofsocks** [comment]
I was not able to reproduce the issue (on MacOS).  Is this issue still persisting?

**Comment by fireproofsocks** [comment]
Will re-open if it can be reproduced.
