### ISSUE TITLE
Obsolete `File.stream!/3` call causes Dialyxir errors in Elixir 1.16

### ISSUE THREAD

**Issue by Hentioe** [fireproofsocks/figlet#4]
Line of code:

https://github.com/fireproofsocks/figlet/blob/301c96fe3b4016e7318d409759afc476b9000852/lib/figlet/parser/font_file_parser.ex#L70

1.16 or above, the typespec of [`File.stream!/3`](https://hexdocs.pm/elixir/1.16.2/File.html#stream!/3) is no longer compatible with such calls.

I'll open a PR to avoid the Dialyzer errors in 1.16.

**Comment by fireproofsocks** [comment]
I think this has now been fixed w version 0.3.2
